### ISSUE TITLE
Privacy - Screenshot notifications contain directory, contains full name

### ISSUE THREAD

**Issue by LordJRazE** [while-loop/runelite-plugins#12]
Just a minor thing: my account on my PC is my full name, when I am streaming the game I would rather not have my real name exposed. Could a toggle be added to remove the message showing the screenshot directory? Currently I can't use the plugin live without doxxing myself

**Comment by while-loop** [comment]
The plugin doesn't control where screenshots are saved. Nor does it send notifications. 

In the "Screenshots" plugin, disable the "Notify when taken" option.

I'm also wondering how you did not run into this issue when other parts of Runelite takes screenshots. Such as leveling up or drops. Since those would also dox you.

**Comment by while-loop** [comment]
I lied. I'll add a config option to disable the notification upon saving a screenshot.

**Comment by LordJRazE** [comment]
Thanks!
