### ISSUE TITLE
Consider adding an icon to Zulrah phases that don't require the player to pray protect from range

### ISSUE THREAD

**Issue by EliasLahham** [while-loop/runelite-plugins#13]
There are several Serp Zulrah phases that just spit out snakes and gas and don't require the player to pray range. Consider adding a small icon on those phases that indicate that the player doesn't have to pray range.

**Comment by badookey** [comment]
I think this would be super handy, happy to have a look into it and maybe get a PR up for this.

**Comment by badookey** [comment]
I see a few different ways of implementing this. I've done some mockups to help explain.
1. Display prayers needed for each phase (and do not display if phase can be done without prayer)
2. Display no-prayer icon on phases where prayer is not required. (@EliasLahham's original suggestion)

I think I prefer approach 1 because 
a) There are also some phases where zulrah will spit clouds for half, then attack for the second half of the phase. Though displaying this in an icon visually may be tricky, I could try a 'half pray' icon for range/mage
b) I dislike the no-prayer icon i've designed (happy for any suggestions!) I think it's not very clear and the red is a bit jarring.

![Mockup with icons](https://user-images.githubusercontent.com/18100566/168215584-df5d4fc5-8eed-4fe8-802d-b091e5a17117.png)

Any feedback @while-loop @EliasLahham ? :)

**Comment by while-loop** [comment]
Looks great!!! I'm leaning more towards the no icons for no prayer. I think it'll become too cluttered for long phases and repetitive for the first and last stages in your screenshot. 

What do you think?

**Comment by EliasLahham** [comment]
This looks great. I agree with omitting the crossed out prayer icon since a player can still use prayer for the snakelings
