### ISSUE TITLE
Inconsistency: Magma rotation skips a step

### ISSUE THREAD

**Issue by Ashe** [while-loop/runelite-plugins#19]
## Expected behaviour

So, when you start the fight you see the following choices:

![image](https://user-images.githubusercontent.com/8940077/92117454-1a26bd80-eded-11ea-93f6-5079a1e64159.png)

You then click whatever you see Zulrah do right? Let's choose option 2 if we see him come back up as green:

![image](https://user-images.githubusercontent.com/8940077/92117536-34609b80-eded-11ea-94ba-f322237b9b49.png)

You see both the current phase you clicked on highlighted, as well as the following phase, so that you can click on it and acknowledge that the phase has moved on in your own time.

## Magma behaviour

So, once again we start at the three choices:

![image](https://user-images.githubusercontent.com/8940077/92117454-1a26bd80-eded-11ea-93f6-5079a1e64159.png)

Zulrah pops up as red, so you click the first option. This is what you see:

![image](https://user-images.githubusercontent.com/8940077/92117688-6a9e1b00-eded-11ea-94f3-e2f0c46d8517.png)

This is very confusing. First of all, I understand that the user needs to make another choice just like after the first phase, however I believe that this is displayed *too soon*. While it serves as a good warning / note that the rotation can split into two, **the step where he turns blue appears without warning**. If you get used to the plugin, you learn to click whatever you see, and follow along. However, this diagram makes it look like we already CHOSE that he was blue, when in fact we only said that Zulrah was red, meaning that my eyes automatically look out for which green spot he will appear at.

I feel like in order to retain consistency, you need to un-darken the magma step (in the far top right corner) to show that that was what the player clicked. It should then show the blue zulrah step ready for the player to click, so that they know after the red zulrah, he's going to turn blue. After then, you can show the two options, much like how the 3 options appear on the first step of the fight.

I do think it is good that the choice is made apparent, but I feel like it's too soon. Perhaps some sort of icon showing that the full rotation isn't known yet would be a good idea, or something?

## Additional note

There is one phase on some rotation where you're expected to move during the phase (where you go from the left to the right side of the map - you have to wait for clouds to disappear and then run before more clouds appear again?). I really like the simplicity of this plugin and I like that there aren't too many markers, but I do feel like it would be useful to give players a heads up that the next phase will require them to move differently otherwise they're going to take a lot of damage.

This is just my perception as a new zulrah killer relying on this plugin :) thank you for making it!

**Comment by while-loop** [comment]
Thanks for submitting this issue!

I created the phase progressions to require a little input from the user as possible. A side effect to that decision is that in the Magma phase that you mentioned it'll feel like the 2nd phase is already completed, but in reality, the plugin is wanted to get the next input from the user.

I think this may be a bug as the outlined green box is supposed to show the _current_ phase. But then would require 2 clicks from the user since we after the red is always a blue, then another decision needs to be made.

Question:
Are you okay, with that extra click to select the phase num 3 once you complete phase num 2?

**Comment by while-loop** [comment]
As for the additional note.. I'd like to add it, but as you mentioned, it could get hairy very quickly. We already have a request for prayer overheads (#13).

The solution to this would most likely having a toggle option for "Show expected movement" or something along those lines.
We should also be able to add the ability to have another toggle for "Show prayerless phases."

To be honest, extending the [images](https://github.com/while-loop/runelite-plugins/tree/zulrah-helper/src/main/resources/phases) for these cases is the reason I haven't added these toggles to the plugin. If you're down for the task and would like to edit the images I'll gladly create the toggle for the plugin utilizing the newly created images. 

But for now, I don't have the motivation/bandwidth to create them :disappointed: .

**Comment by Ashe** [comment]
Thank you for replying and I understand your position on wanting less input as possible! However, for me, I actually *want* that input. Some people are visual, some people are methodical etc. For me, its not about *seeing* what's coming next and seeing the entire rotation, its knowing how far along I am in the current one. Actually clicking that phase and acknowledging it is the thing that's helped me kill Zulrah, and is the sole reason why your plugin has been the only way I've been able to really do this easily, as static pictures just make me lose where I am. It's perfect, it greys out information I don't need to see, it shows me where I should be standing *right now*, and it tells me the next step of where I should go. The entire phase is irrelevant from my point of a view as a learner :) 

I'd be okay, but like with most things in games, making it configurable is probably the best idea in case someone dislikes what I want.

I don't think it would be too detrimental to keep it exactly how it is, except un-grey the top right button and have the blue step clickable. You could still show the 'select a phase' bit for people who want to skip to it (since it is a consistent thing across the board that if you forget to click a phase, you can just click the one you're on rather than clicking through the ones you missed).

So for me, I don't mind and would appreciate the extra click, but honestly you could get away with just fixing which phase is the current one and making the blue one clickable - you don't need to delay the selection bit really as long as I can process the current step. I personally felt a bit confused seeing the select phase area before noticing the blue phase, but that's mostly because the blue phase is 'current' and therefore I didn't examine it closely enough.

Ungrey the red, make the blue clickable, do whatever you like with the 'select a phase' area. I think that'll be just fine :) 

Honestly I don't mind about the prayers and stuff, I'm very new to it and blue=pray mage is already good enough for me. I'll learn when I don't need to pray in my own time - the essential information is *what* I need to pray - as long as I'm praying I will be safe, even if it does waste a little bit on those phases where he's just making clouds.

The only one I was saying, is that there are a few phases where you can't do the run before / after, and you have to run while shooting zulrah as the clouds despawn / as they spawn. I feel like these are a bit of a special case as they can catch you out. I attack zulrah, then run as he goes down, so knowing when I need to remember these special cases is a tough one for me and I always get hit by a cloud - only small damage but its a bad habit. That's all I meant really, not like another 30 images, just a redesign on some of them? :) 

Thank you for the amazing plugin!

**Comment by anon2828226** [comment]
I am actually floored at how goofy this "little inconsistency" and how off the reason given for it existing is. literally just border in green the correct phase, instead of randomly making people think they are in the wrong phase or clicked the wrong option, and allow them to either click the next phase as it comes, instead of clicking for them the exact wrong phase before, or just only click the next phase after that whichever of the two it ends up.

No matter how you might misconceive the reason for having made that choice ask ideally before why would a random user know and understand all that having just started a boss fight? at the very least add a little description entry for your reasoning before letting them use the plugin for the first time. better just to display correct info and risk a completely optional second click instead of making the user reverse or derive your reasoning probably in the middle of a boss fight.

Even worse than all this is how trash the general status quo around Zulrah is. This plugin provides no additional value over a browser page meanwhile the fight caves have game-world aware/dynamic tile highlights for where the next monster/boss is coming and info on what prayer (or maybe attack the monster uses) written over them.  All this while bots are using flawless real time info and automation all day long on basically every world. It is categorically ridiculous that jagex doesn't allow a plugin to while not displaying anything in the game-world/space use info from the game given all that. 
If the plugin just showed the current phase and the next phase this would be 1/10th of what is currently allowed in the fight caves (and of course 1/100 of what most "accounts" going in there use). As it is newbies trying to learn bossing probably the first time have to do essentially a second prayer switch way off to the side while reading an infographic excel spreadsheet all while trying to play the actual game. this is a quit moment in a big way. <----

So many people resort to memorizing a single rotation and so spend their time teleporting in and out about 5 times for every 1 attempt and in my testing for ironmen genuinely spending more than 65% of the time for every one attempt given the time it takes to bring zulrah to 200 health walking across zul andra between the memorized rotation. I finally got 1 kc in zulrah but felt like I spent more time fucking with the zulrah helper than actually playing the game and am burnt way out. I can't imagine coming back to zulrah ever again maybe if i get a twisted bow or something someday. for now I think my membership will lapse and when I come back later in the year or whatever I'll do vorkath or fight caves if i do any bossing.

**Comment by while-loop** [comment]
Why are you bringing bots into the conversation? 
Have you read the rules? The previous zulrah plugin was already banned. 

https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1

Relax.

**Comment by anon2828226** [comment]
I knew the plugin was banned that is inherent to the point. there are two things going on. everything before "Even worse than all this..." is not directly related to the plugin, accepts the current situation and is directly on point with this plugin if that is your limit. everything after is about the ban and how the rules for plugins made after are not consistently enforced and never made sense in their full scope.

**Comment by raiyni** [comment]
I believe fixed in 6690b2685636d83a31f54b173c6a7d3c7796c5b3
