### ISSUE TITLE
Zulrah Helper: Detect phase in addition to user input

### ISSUE THREAD

**Issue by Intecpsp** [while-loop/runelite-plugins#59]
It would be awesome if this plugin could detect the phase of Zulrah instead of requiring user input. This would resemble the [Fight Caves Spawn Predictor](https://runelite.net/plugin-hub/show/spawnpredictor). It detects the wave with no user input, and lets the user know what is next and where it will be. 

As a new learner to Zulrah I want to take advantage of this plugin, but don't have the muscle memory or mental capacity to work the game and this plugin right now. If this plugin could assist with the order of things and where to be by itself, I feel it would help me and others pick and learn Zulrah quicker.

**Comment by while-loop** [comment]
The original Zulrah plugin was removed by Jagex because of its features. 

This plugin was created to be completely manual to stay within their rules (https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1). We're not allowed to show where to stand or which prayers to select. 

These are against guidelines. 

> Next attack prediction (timing or attack style) Projectile targets, or target locations, as well as impact locations
> Prayer switching indicators
> Attack counters
> Anything that automatically indicates where to stand, or not to stand. This applies to only automatic indicators, and not tiles which have been manually marked.

**Comment by Intecpsp** [comment]
What if it was the same plugin it is today, just automating the first few rotations (the manual entry today).
